name: Coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}=${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Run test coverage
        run: pnpm test:coverage

      - name: Upload code coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          fail_ci_if_error: true
